spring:
  application:
    name: SmartBet
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.kckimbkobioqyudqnzvg
    password: TheInvinciblesProject@35
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li8Lm4OC4u6A6LfN
            client-secret: 9ef36f34fa68771e9e8f67844b718237b3e8544a
            scope: read:user,user:email

          google:
            client-id: 462297550542-jlh81q4c3uho2afpl42kejgml7gkv7u3.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email